language: en

pipeline: supervised_embeddings

policies:
  - name: KerasPolicy
  - name: "FallbackPolicy"
    nlu_threshold: 0.7
    core_threshold: 0.6
    fallback_action_name: "utter_ask_rephrase"
  - name: MemoizationPolicy
  - name: MappingPolicy